apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: project
spec:
  ports:
  - name: db-svc
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
        containers:
        - image: 192.168.0.91:5000/db:polar
          imagePullPolicy: Always 
          name: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "1234"
